name: Nuclei - Vulnerability Scan

on:
    workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: http://testphp.vulnweb.com
          flags: "-severity info -stats"
          github-report: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log
